"""Data models for JARVIS Personal Assistant."""

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field


class EmailAttachment(BaseModel):
    """Represents an email attachment."""
    filename: str
    content_type: str
    size_bytes: Optional[int] = None


class EmailMessage(BaseModel):
    """Represents a standardized email message retrieved from any backend."""
    id: str = Field(description="Unique email identifier")
    thread_id: Optional[str] = Field(default=None, description="Thread identifier if available")
    sender: str = Field(description="Sender name and email address")
    recipient: str = Field(default="", description="Recipient email address")
    subject: str = Field(description="Email subject line")
    date: Optional[datetime] = Field(default=None, description="Timestamp of the email")
    snippet: str = Field(default="", description="Short snippet/preview of the email")
    body_text: str = Field(description="Sanitized plain text body")
    body_html: Optional[str] = Field(default=None, description="Raw HTML body if available")
    is_unread: bool = Field(default=True, description="Whether the email is currently unread")
    labels: List[str] = Field(default_factory=list, description="Labels/folders associated with the email")
    attachments: List[EmailAttachment] = Field(default_factory=list, description="List of email attachments")
    source: str = Field(default="unknown", description="Source provider: gmail, imap, mock")


class ActionItem(BaseModel):
    """Represents a specific action item extracted from an email."""
    task: str
    assignee_or_sender: str
    deadline: Optional[str] = None
    urgency: str = Field(default="Normal", description="Urgency: Low, Normal, High, Critical")


class EmailBrief(BaseModel):
    """Individual email summary by JARVIS."""
    email_id: str
    sender: str
    subject: str
    urgency: str = "Normal"  # Critical, High, Medium, Low
    key_points: List[str] = Field(default_factory=list)
    action_items: List[str] = Field(default_factory=list)
    deadline: Optional[str] = None


class JarvisBriefing(BaseModel):
    """Complete briefing generated by JARVIS."""
    executive_summary: str
    total_emails_processed: int
    critical_alerts: List[str] = Field(default_factory=list)
    action_items: List[ActionItem] = Field(default_factory=list)
    email_briefs: List[EmailBrief] = Field(default_factory=list)
    raw_response: str = ""
    timestamp: datetime = Field(default_factory=datetime.now)
